// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'model.dart';

// **************************************************************************
// SqfEntityGenerator
// **************************************************************************

//  These classes was generated by SqfEntity
//  Copyright (c) 2019, All rights reserved. Use of this source code is governed by a
//  Apache license that can be found in the LICENSE file.

//  To use these SqfEntity classes do following:
//  - import model.dart into where to use
//  - start typing ex:FRCMCheckBoxData.select()... (add a few filters with fluent methods)...(add orderBy/orderBydesc if you want)...
//  - and then just put end of filters / or end of only select()  toSingle() / or toList()
//  - you can select one or return List<yourObject> by your filters and orders
//  - also you can batch update or batch delete by using delete/update methods instead of tosingle/tolist methods
//    Enjoy.. Huseyin Tokpunar

// ignore_for_file:
// BEGIN TABLES
// FRCMCheckBoxData TABLE
class TableFRCMCheckBoxData extends SqfEntityTableBase {
  TableFRCMCheckBoxData() {
    // declare properties of EntityTable
    tableName = 'FRCMCheckBoxData';
    primaryKeyName = 'id';
    primaryKeyType = PrimaryKeyType.integer_auto_incremental;
    useSoftDeleting = true;
    // when useSoftDeleting is true, creates a field named 'isDeleted' on the table, and set to '1' this field when item deleted (does not hard delete)

    // declare fields
    fields = [
      SqfEntityFieldBase('userName', DbType.text, isNotNull: false),
      SqfEntityFieldBase('userPassword', DbType.text, isNotNull: false),
      SqfEntityFieldBase('selectedProject', DbType.text, isNotNull: false),
      SqfEntityFieldBase('selectedPhase', DbType.text, isNotNull: false),
      SqfEntityFieldBase('selectedSubPhase', DbType.text, isNotNull: false),
      SqfEntityFieldBase('selectedCheckBoxTitle', DbType.text,
          isNotNull: false),
      SqfEntityFieldBase('selectedCheckBoxStatus', DbType.text,
          isNotNull: false),
      SqfEntityFieldBase('selectedCheckBoxComments', DbType.text,
          isNotNull: false),
    ];
    super.init();
  }
  static SqfEntityTableBase _instance;
  static SqfEntityTableBase get getInstance {
    return _instance = _instance ?? TableFRCMCheckBoxData();
  }
}
// END TABLES

// BEGIN SEQUENCES
// identity SEQUENCE
class SequenceIdentitySequence extends SqfEntitySequenceBase {
  SequenceIdentitySequence() {
    sequenceName = 'identity';
    maxValue =
        9007199254740991; /* optional. default is max int (9.223.372.036.854.775.807) */
    cycle = false; /* optional. default is false; */
    minValue = 0; /* optional. default is 0 */
    incrementBy = 1; /* optional. default is 1 */
    startWith = 0; /* optional. default is 0 */
    super.init();
  }
  static SequenceIdentitySequence _instance;
  static SequenceIdentitySequence get getInstance {
    return _instance = _instance ?? SequenceIdentitySequence();
  }
}
// END SEQUENCES

// BEGIN DATABASE MODEL
class EcpsFrcmMmodel extends SqfEntityModelProvider {
  EcpsFrcmMmodel() {
    databaseName = FRCMmodel.databaseName;
    password = FRCMmodel.password;
    dbVersion = FRCMmodel.dbVersion;
    databaseTables = [
      TableFRCMCheckBoxData.getInstance,
    ];

    sequences = [
      SequenceIdentitySequence.getInstance,
    ];

    bundledDatabasePath = FRCMmodel
        .bundledDatabasePath; //'assets/sample.db'; // This value is optional. When bundledDatabasePath is empty then EntityBase creats a new database when initializing the database
  }
  Map<String, dynamic> getControllers() {
    final controllers = <String, dynamic>{};
    controllers['frcmcheckboxdata'] = FRCMCheckBoxDataController.getController;

    return controllers;
  }
}
// END DATABASE MODEL

// BEGIN ENTITIES
// region FRCMCheckBoxData
class FRCMCheckBoxData {
  FRCMCheckBoxData(
      {this.id,
      this.userName,
      this.userPassword,
      this.selectedProject,
      this.selectedPhase,
      this.selectedSubPhase,
      this.selectedCheckBoxTitle,
      this.selectedCheckBoxStatus,
      this.selectedCheckBoxComments,
      this.isDeleted}) {
    _setDefaultValues();
  }
  FRCMCheckBoxData.withFields(
      this.userName,
      this.userPassword,
      this.selectedProject,
      this.selectedPhase,
      this.selectedSubPhase,
      this.selectedCheckBoxTitle,
      this.selectedCheckBoxStatus,
      this.selectedCheckBoxComments,
      this.isDeleted) {
    _setDefaultValues();
  }
  FRCMCheckBoxData.withId(
      this.id,
      this.userName,
      this.userPassword,
      this.selectedProject,
      this.selectedPhase,
      this.selectedSubPhase,
      this.selectedCheckBoxTitle,
      this.selectedCheckBoxStatus,
      this.selectedCheckBoxComments,
      this.isDeleted) {
    _setDefaultValues();
  }
  FRCMCheckBoxData.fromMap(Map<String, dynamic> o,
      {bool setDefaultValues = true}) {
    if (setDefaultValues) {
      _setDefaultValues();
    }
    id = int.tryParse(o['id'].toString());
    if (o['userName'] != null) {
      userName = o['userName'] as String;
    }
    if (o['userPassword'] != null) {
      userPassword = o['userPassword'] as String;
    }
    if (o['selectedProject'] != null) {
      selectedProject = o['selectedProject'] as String;
    }
    if (o['selectedPhase'] != null) {
      selectedPhase = o['selectedPhase'] as String;
    }
    if (o['selectedSubPhase'] != null) {
      selectedSubPhase = o['selectedSubPhase'] as String;
    }
    if (o['selectedCheckBoxTitle'] != null) {
      selectedCheckBoxTitle = o['selectedCheckBoxTitle'] as String;
    }
    if (o['selectedCheckBoxStatus'] != null) {
      selectedCheckBoxStatus = o['selectedCheckBoxStatus'] as String;
    }
    if (o['selectedCheckBoxComments'] != null) {
      selectedCheckBoxComments = o['selectedCheckBoxComments'] as String;
    }
    isDeleted = o['isDeleted'] != null
        ? o['isDeleted'] == 1 || o['isDeleted'] == true
        : null;
  }
  // FIELDS (FRCMCheckBoxData)
  int id;
  String userName;
  String userPassword;
  String selectedProject;
  String selectedPhase;
  String selectedSubPhase;
  String selectedCheckBoxTitle;
  String selectedCheckBoxStatus;
  String selectedCheckBoxComments;
  bool isDeleted;

  BoolResult saveResult;
  // end FIELDS (FRCMCheckBoxData)

  static const bool _softDeleteActivated = true;
  FRCMCheckBoxDataManager __mnFRCMCheckBoxData;

  FRCMCheckBoxDataManager get _mnFRCMCheckBoxData {
    return __mnFRCMCheckBoxData =
        __mnFRCMCheckBoxData ?? FRCMCheckBoxDataManager();
  }

  // METHODS
  Map<String, dynamic> toMap(
      {bool forQuery = false, bool forJson = false, bool forView = false}) {
    final map = <String, dynamic>{};
    if (id != null) {
      map['id'] = id;
    }
    if (userName != null) {
      map['userName'] = userName;
    }

    if (userPassword != null) {
      map['userPassword'] = userPassword;
    }

    if (selectedProject != null) {
      map['selectedProject'] = selectedProject;
    }

    if (selectedPhase != null) {
      map['selectedPhase'] = selectedPhase;
    }

    if (selectedSubPhase != null) {
      map['selectedSubPhase'] = selectedSubPhase;
    }

    if (selectedCheckBoxTitle != null) {
      map['selectedCheckBoxTitle'] = selectedCheckBoxTitle;
    }

    if (selectedCheckBoxStatus != null) {
      map['selectedCheckBoxStatus'] = selectedCheckBoxStatus;
    }

    if (selectedCheckBoxComments != null) {
      map['selectedCheckBoxComments'] = selectedCheckBoxComments;
    }

    if (isDeleted != null) {
      map['isDeleted'] = forQuery ? (isDeleted ? 1 : 0) : isDeleted;
    }

    return map;
  }

  Future<Map<String, dynamic>> toMapWithChildren(
      [bool forQuery = false,
      bool forJson = false,
      bool forView = false]) async {
    final map = <String, dynamic>{};
    if (id != null) {
      map['id'] = id;
    }
    if (userName != null) {
      map['userName'] = userName;
    }

    if (userPassword != null) {
      map['userPassword'] = userPassword;
    }

    if (selectedProject != null) {
      map['selectedProject'] = selectedProject;
    }

    if (selectedPhase != null) {
      map['selectedPhase'] = selectedPhase;
    }

    if (selectedSubPhase != null) {
      map['selectedSubPhase'] = selectedSubPhase;
    }

    if (selectedCheckBoxTitle != null) {
      map['selectedCheckBoxTitle'] = selectedCheckBoxTitle;
    }

    if (selectedCheckBoxStatus != null) {
      map['selectedCheckBoxStatus'] = selectedCheckBoxStatus;
    }

    if (selectedCheckBoxComments != null) {
      map['selectedCheckBoxComments'] = selectedCheckBoxComments;
    }

    if (isDeleted != null) {
      map['isDeleted'] = forQuery ? (isDeleted ? 1 : 0) : isDeleted;
    }

    return map;
  }

  /// This method returns Json String [FRCMCheckBoxData]
  String toJson() {
    return json.encode(toMap(forJson: true));
  }

  /// This method returns Json String [FRCMCheckBoxData]
  Future<String> toJsonWithChilds() async {
    return json.encode(await toMapWithChildren(false, true));
  }

  List<dynamic> toArgs() {
    return [
      userName,
      userPassword,
      selectedProject,
      selectedPhase,
      selectedSubPhase,
      selectedCheckBoxTitle,
      selectedCheckBoxStatus,
      selectedCheckBoxComments,
      isDeleted
    ];
  }

  List<dynamic> toArgsWithIds() {
    return [
      id,
      userName,
      userPassword,
      selectedProject,
      selectedPhase,
      selectedSubPhase,
      selectedCheckBoxTitle,
      selectedCheckBoxStatus,
      selectedCheckBoxComments,
      isDeleted
    ];
  }

  static Future<List<FRCMCheckBoxData>> fromWebUrl(String url,
      {Map<String, String> headers}) async {
    try {
      final response = await http.get(url, headers: headers);
      return await fromJson(response.body);
    } catch (e) {
      print(
          'SQFENTITY ERROR FRCMCheckBoxData.fromWebUrl: ErrorMessage: ${e.toString()}');
      return null;
    }
  }

  Future<http.Response> postUrl(String url, {Map<String, String> headers}) {
    return http.post(url, headers: headers, body: toJson());
  }

  static Future<List<FRCMCheckBoxData>> fromJson(String jsonBody) async {
    final Iterable list = await json.decode(jsonBody) as Iterable;
    var objList = <FRCMCheckBoxData>[];
    try {
      objList = list
          .map((frcmcheckboxdata) => FRCMCheckBoxData.fromMap(
              frcmcheckboxdata as Map<String, dynamic>))
          .toList();
    } catch (e) {
      print(
          'SQFENTITY ERROR FRCMCheckBoxData.fromJson: ErrorMessage: ${e.toString()}');
    }
    return objList;
  }

  static Future<List<FRCMCheckBoxData>> fromMapList(List<dynamic> data,
      {bool preload = false,
      List<String> preloadFields,
      bool loadParents = false,
      List<String> loadedFields,
      bool setDefaultValues = true}) async {
    final List<FRCMCheckBoxData> objList = <FRCMCheckBoxData>[];
    loadedFields = loadedFields ?? [];
    for (final map in data) {
      final obj = FRCMCheckBoxData.fromMap(map as Map<String, dynamic>,
          setDefaultValues: setDefaultValues);

      objList.add(obj);
    }
    return objList;
  }

  /// returns FRCMCheckBoxData by ID if exist, otherwise returns null
  ///
  /// Primary Keys: int id
  ///
  /// bool preload: if true, loads all related child objects (Set preload to true if you want to load all fields related to child or parent)
  ///
  /// ex: getById(preload:true) -> Loads all related objects
  ///
  /// List<String> preloadFields: specify the fields you want to preload (preload parameter's value should also be "true")
  ///
  /// ex: getById(preload:true, preloadFields:['plField1','plField2'... etc])  -> Loads only certain fields what you specified
  ///
  /// bool loadParents: if true, loads all parent objects until the object has no parent

  ///
  /// <returns>returns FRCMCheckBoxData if exist, otherwise returns null
  Future<FRCMCheckBoxData> getById(int id,
      {bool preload = false,
      List<String> preloadFields,
      bool loadParents = false,
      List<String> loadedFields}) async {
    if (id == null) {
      return null;
    }
    FRCMCheckBoxData obj;
    final data = await _mnFRCMCheckBoxData.getById([id]);
    if (data.length != 0) {
      obj = FRCMCheckBoxData.fromMap(data[0] as Map<String, dynamic>);
    } else {
      obj = null;
    }
    return obj;
  }

  /// Saves the (FRCMCheckBoxData) object. If the id field is null, saves as a new record and returns new id, if id is not null then updates record

  /// <returns>Returns id
  Future<int> save() async {
    if (id == null || id == 0) {
      id = await _mnFRCMCheckBoxData.insert(this);
    } else {
      // id= await _upsert(); // removed in sqfentity_gen 1.3.0+6
      await _mnFRCMCheckBoxData.update(this);
    }

    return id;
  }

  /// saveAs FRCMCheckBoxData. Returns a new Primary Key value of FRCMCheckBoxData

  /// <returns>Returns a new Primary Key value of FRCMCheckBoxData
  Future<int> saveAs() async {
    id = null;

    return save();
  }

  /// saveAll method saves the sent List<FRCMCheckBoxData> as a bulk in one transaction
  ///
  /// Returns a <List<BoolResult>>
  static Future<List<dynamic>> saveAll(
      List<FRCMCheckBoxData> frcmcheckboxdatas) async {
    // final results = _mnFRCMCheckBoxData.saveAll('INSERT OR REPLACE INTO FRCMCheckBoxData (id,userName, userPassword, selectedProject, selectedPhase, selectedSubPhase, selectedCheckBoxTitle, selectedCheckBoxStatus, selectedCheckBoxComments,isDeleted)  VALUES (?,?,?,?,?,?,?,?,?,?)',frcmcheckboxdatas);
    // return results; removed in sqfentity_gen 1.3.0+6
    await EcpsFrcmMmodel().batchStart();
    for (final obj in frcmcheckboxdatas) {
      await obj.save();
    }
    //    return EcpsFrcmMmodel().batchCommit();
    final result = await EcpsFrcmMmodel().batchCommit();
    for (int i = 0; i < frcmcheckboxdatas.length; i++) {
      if (frcmcheckboxdatas[i].id == null) {
        frcmcheckboxdatas[i].id = result[i] as int;
      }
    }

    return result;
  }

  /// Updates if the record exists, otherwise adds a new row

  /// <returns>Returns id
  Future<int> upsert() async {
    try {
      if (await _mnFRCMCheckBoxData.rawInsert(
              'INSERT OR REPLACE INTO FRCMCheckBoxData (id,userName, userPassword, selectedProject, selectedPhase, selectedSubPhase, selectedCheckBoxTitle, selectedCheckBoxStatus, selectedCheckBoxComments,isDeleted)  VALUES (?,?,?,?,?,?,?,?,?,?)',
              [
                id,
                userName,
                userPassword,
                selectedProject,
                selectedPhase,
                selectedSubPhase,
                selectedCheckBoxTitle,
                selectedCheckBoxStatus,
                selectedCheckBoxComments,
                isDeleted
              ]) ==
          1) {
        saveResult = BoolResult(
            success: true,
            successMessage: 'FRCMCheckBoxData id=$id updated successfully');
      } else {
        saveResult = BoolResult(
            success: false,
            errorMessage: 'FRCMCheckBoxData id=$id did not update');
      }
      return id;
    } catch (e) {
      saveResult = BoolResult(
          success: false,
          errorMessage: 'FRCMCheckBoxData Save failed. Error: ${e.toString()}');
      return 0;
    }
  }

  /// inserts or replaces the sent List<<FRCMCheckBoxData>> as a bulk in one transaction.
  ///
  /// upsertAll() method is faster then saveAll() method. upsertAll() should be used when you are sure that the primary key is greater than zero
  ///
  /// Returns a BoolCommitResult
  Future<BoolCommitResult> upsertAll(
      List<FRCMCheckBoxData> frcmcheckboxdatas) async {
    final results = await _mnFRCMCheckBoxData.rawInsertAll(
        'INSERT OR REPLACE INTO FRCMCheckBoxData (id,userName, userPassword, selectedProject, selectedPhase, selectedSubPhase, selectedCheckBoxTitle, selectedCheckBoxStatus, selectedCheckBoxComments,isDeleted)  VALUES (?,?,?,?,?,?,?,?,?,?)',
        frcmcheckboxdatas);
    return results;
  }

  /// Deletes FRCMCheckBoxData

  /// <returns>BoolResult res.success=Deleted, not res.success=Can not deleted
  Future<BoolResult> delete([bool hardDelete = false]) async {
    print('SQFENTITIY: delete FRCMCheckBoxData invoked (id=$id)');
    if (!_softDeleteActivated || hardDelete || isDeleted) {
      return _mnFRCMCheckBoxData
          .delete(QueryParams(whereString: 'id=?', whereArguments: [id]));
    } else {
      return _mnFRCMCheckBoxData.updateBatch(
          QueryParams(whereString: 'id=?', whereArguments: [id]),
          {'isDeleted': 1});
    }
  }

  /// Recover FRCMCheckBoxData>

  /// <returns>BoolResult res.success=Recovered, not res.success=Can not recovered
  Future<BoolResult> recover([bool recoverChilds = true]) async {
    print('SQFENTITIY: recover FRCMCheckBoxData invoked (id=$id)');
    {
      return _mnFRCMCheckBoxData.updateBatch(
          QueryParams(whereString: 'id=?', whereArguments: [id]),
          {'isDeleted': 0});
    }
  }

  FRCMCheckBoxDataFilterBuilder select(
      {List<String> columnsToSelect, bool getIsDeleted}) {
    return FRCMCheckBoxDataFilterBuilder(this)
      .._getIsDeleted = getIsDeleted == true
      ..qparams.selectColumns = columnsToSelect;
  }

  FRCMCheckBoxDataFilterBuilder distinct(
      {List<String> columnsToSelect, bool getIsDeleted}) {
    return FRCMCheckBoxDataFilterBuilder(this)
      .._getIsDeleted = getIsDeleted == true
      ..qparams.selectColumns = columnsToSelect
      ..qparams.distinct = true;
  }

  void _setDefaultValues() {
    isDeleted = isDeleted ?? false;
  }
  // END METHODS
  // CUSTOM CODES
  /*
      you must define customCode property of your SqfEntityTable constant for ex:
      const tablePerson = SqfEntityTable(
      tableName: 'person',
      primaryKeyName: 'id',
      primaryKeyType: PrimaryKeyType.integer_auto_incremental,
      fields: [
        SqfEntityField('firstName', DbType.text),
        SqfEntityField('lastName', DbType.text),
      ],
      customCode: '''
       String fullName()
       { 
         return '$firstName $lastName';
       }
      ''');
     */
  // END CUSTOM CODES
}
// endregion frcmcheckboxdata

// region FRCMCheckBoxDataField
class FRCMCheckBoxDataField extends SearchCriteria {
  FRCMCheckBoxDataField(this.frcmcheckboxdataFB) {
    param = DbParameter();
  }
  DbParameter param;
  String _waitingNot = '';
  FRCMCheckBoxDataFilterBuilder frcmcheckboxdataFB;

  FRCMCheckBoxDataField get not {
    _waitingNot = ' NOT ';
    return this;
  }

  FRCMCheckBoxDataFilterBuilder equals(dynamic pValue) {
    param.expression = '=';
    frcmcheckboxdataFB._addedBlocks = _waitingNot == ''
        ? setCriteria(pValue, frcmcheckboxdataFB.parameters, param,
            SqlSyntax.EQuals, frcmcheckboxdataFB._addedBlocks)
        : setCriteria(pValue, frcmcheckboxdataFB.parameters, param,
            SqlSyntax.NotEQuals, frcmcheckboxdataFB._addedBlocks);
    _waitingNot = '';
    frcmcheckboxdataFB
            ._addedBlocks.needEndBlock[frcmcheckboxdataFB._blockIndex] =
        frcmcheckboxdataFB._addedBlocks.retVal;
    return frcmcheckboxdataFB;
  }

  FRCMCheckBoxDataFilterBuilder equalsOrNull(dynamic pValue) {
    param.expression = '=';
    frcmcheckboxdataFB._addedBlocks = _waitingNot == ''
        ? setCriteria(pValue, frcmcheckboxdataFB.parameters, param,
            SqlSyntax.EQualsOrNull, frcmcheckboxdataFB._addedBlocks)
        : setCriteria(pValue, frcmcheckboxdataFB.parameters, param,
            SqlSyntax.NotEQualsOrNull, frcmcheckboxdataFB._addedBlocks);
    _waitingNot = '';
    frcmcheckboxdataFB
            ._addedBlocks.needEndBlock[frcmcheckboxdataFB._blockIndex] =
        frcmcheckboxdataFB._addedBlocks.retVal;
    return frcmcheckboxdataFB;
  }

  FRCMCheckBoxDataFilterBuilder isNull() {
    frcmcheckboxdataFB._addedBlocks = setCriteria(
        0,
        frcmcheckboxdataFB.parameters,
        param,
        SqlSyntax.IsNULL.replaceAll(SqlSyntax.notKeyword, _waitingNot),
        frcmcheckboxdataFB._addedBlocks);
    _waitingNot = '';
    frcmcheckboxdataFB
            ._addedBlocks.needEndBlock[frcmcheckboxdataFB._blockIndex] =
        frcmcheckboxdataFB._addedBlocks.retVal;
    return frcmcheckboxdataFB;
  }

  FRCMCheckBoxDataFilterBuilder contains(dynamic pValue) {
    if (pValue != null) {
      frcmcheckboxdataFB._addedBlocks = setCriteria(
          '%${pValue.toString()}%',
          frcmcheckboxdataFB.parameters,
          param,
          SqlSyntax.Contains.replaceAll(SqlSyntax.notKeyword, _waitingNot),
          frcmcheckboxdataFB._addedBlocks);
      _waitingNot = '';
      frcmcheckboxdataFB
              ._addedBlocks.needEndBlock[frcmcheckboxdataFB._blockIndex] =
          frcmcheckboxdataFB._addedBlocks.retVal;
    }
    return frcmcheckboxdataFB;
  }

  FRCMCheckBoxDataFilterBuilder startsWith(dynamic pValue) {
    if (pValue != null) {
      frcmcheckboxdataFB._addedBlocks = setCriteria(
          '${pValue.toString()}%',
          frcmcheckboxdataFB.parameters,
          param,
          SqlSyntax.Contains.replaceAll(SqlSyntax.notKeyword, _waitingNot),
          frcmcheckboxdataFB._addedBlocks);
      _waitingNot = '';
      frcmcheckboxdataFB
              ._addedBlocks.needEndBlock[frcmcheckboxdataFB._blockIndex] =
          frcmcheckboxdataFB._addedBlocks.retVal;
      frcmcheckboxdataFB
              ._addedBlocks.needEndBlock[frcmcheckboxdataFB._blockIndex] =
          frcmcheckboxdataFB._addedBlocks.retVal;
    }
    return frcmcheckboxdataFB;
  }

  FRCMCheckBoxDataFilterBuilder endsWith(dynamic pValue) {
    if (pValue != null) {
      frcmcheckboxdataFB._addedBlocks = setCriteria(
          '%${pValue.toString()}',
          frcmcheckboxdataFB.parameters,
          param,
          SqlSyntax.Contains.replaceAll(SqlSyntax.notKeyword, _waitingNot),
          frcmcheckboxdataFB._addedBlocks);
      _waitingNot = '';
      frcmcheckboxdataFB
              ._addedBlocks.needEndBlock[frcmcheckboxdataFB._blockIndex] =
          frcmcheckboxdataFB._addedBlocks.retVal;
    }
    return frcmcheckboxdataFB;
  }

  FRCMCheckBoxDataFilterBuilder between(dynamic pFirst, dynamic pLast) {
    if (pFirst != null && pLast != null) {
      frcmcheckboxdataFB._addedBlocks = setCriteria(
          pFirst,
          frcmcheckboxdataFB.parameters,
          param,
          SqlSyntax.Between.replaceAll(SqlSyntax.notKeyword, _waitingNot),
          frcmcheckboxdataFB._addedBlocks,
          pLast);
    } else if (pFirst != null) {
      if (_waitingNot != '') {
        frcmcheckboxdataFB._addedBlocks = setCriteria(
            pFirst,
            frcmcheckboxdataFB.parameters,
            param,
            SqlSyntax.LessThan,
            frcmcheckboxdataFB._addedBlocks);
      } else {
        frcmcheckboxdataFB._addedBlocks = setCriteria(
            pFirst,
            frcmcheckboxdataFB.parameters,
            param,
            SqlSyntax.GreaterThanOrEquals,
            frcmcheckboxdataFB._addedBlocks);
      }
    } else if (pLast != null) {
      if (_waitingNot != '') {
        frcmcheckboxdataFB._addedBlocks = setCriteria(
            pLast,
            frcmcheckboxdataFB.parameters,
            param,
            SqlSyntax.GreaterThan,
            frcmcheckboxdataFB._addedBlocks);
      } else {
        frcmcheckboxdataFB._addedBlocks = setCriteria(
            pLast,
            frcmcheckboxdataFB.parameters,
            param,
            SqlSyntax.LessThanOrEquals,
            frcmcheckboxdataFB._addedBlocks);
      }
    }
    _waitingNot = '';
    frcmcheckboxdataFB
            ._addedBlocks.needEndBlock[frcmcheckboxdataFB._blockIndex] =
        frcmcheckboxdataFB._addedBlocks.retVal;
    return frcmcheckboxdataFB;
  }

  FRCMCheckBoxDataFilterBuilder greaterThan(dynamic pValue) {
    param.expression = '>';
    frcmcheckboxdataFB._addedBlocks = _waitingNot == ''
        ? setCriteria(pValue, frcmcheckboxdataFB.parameters, param,
            SqlSyntax.GreaterThan, frcmcheckboxdataFB._addedBlocks)
        : setCriteria(pValue, frcmcheckboxdataFB.parameters, param,
            SqlSyntax.LessThanOrEquals, frcmcheckboxdataFB._addedBlocks);
    _waitingNot = '';
    frcmcheckboxdataFB
            ._addedBlocks.needEndBlock[frcmcheckboxdataFB._blockIndex] =
        frcmcheckboxdataFB._addedBlocks.retVal;
    return frcmcheckboxdataFB;
  }

  FRCMCheckBoxDataFilterBuilder lessThan(dynamic pValue) {
    param.expression = '<';
    frcmcheckboxdataFB._addedBlocks = _waitingNot == ''
        ? setCriteria(pValue, frcmcheckboxdataFB.parameters, param,
            SqlSyntax.LessThan, frcmcheckboxdataFB._addedBlocks)
        : setCriteria(pValue, frcmcheckboxdataFB.parameters, param,
            SqlSyntax.GreaterThanOrEquals, frcmcheckboxdataFB._addedBlocks);
    _waitingNot = '';
    frcmcheckboxdataFB
            ._addedBlocks.needEndBlock[frcmcheckboxdataFB._blockIndex] =
        frcmcheckboxdataFB._addedBlocks.retVal;
    return frcmcheckboxdataFB;
  }

  FRCMCheckBoxDataFilterBuilder greaterThanOrEquals(dynamic pValue) {
    param.expression = '>=';
    frcmcheckboxdataFB._addedBlocks = _waitingNot == ''
        ? setCriteria(pValue, frcmcheckboxdataFB.parameters, param,
            SqlSyntax.GreaterThanOrEquals, frcmcheckboxdataFB._addedBlocks)
        : setCriteria(pValue, frcmcheckboxdataFB.parameters, param,
            SqlSyntax.LessThan, frcmcheckboxdataFB._addedBlocks);
    _waitingNot = '';
    frcmcheckboxdataFB
            ._addedBlocks.needEndBlock[frcmcheckboxdataFB._blockIndex] =
        frcmcheckboxdataFB._addedBlocks.retVal;
    return frcmcheckboxdataFB;
  }

  FRCMCheckBoxDataFilterBuilder lessThanOrEquals(dynamic pValue) {
    param.expression = '<=';
    frcmcheckboxdataFB._addedBlocks = _waitingNot == ''
        ? setCriteria(pValue, frcmcheckboxdataFB.parameters, param,
            SqlSyntax.LessThanOrEquals, frcmcheckboxdataFB._addedBlocks)
        : setCriteria(pValue, frcmcheckboxdataFB.parameters, param,
            SqlSyntax.GreaterThan, frcmcheckboxdataFB._addedBlocks);
    _waitingNot = '';
    frcmcheckboxdataFB
            ._addedBlocks.needEndBlock[frcmcheckboxdataFB._blockIndex] =
        frcmcheckboxdataFB._addedBlocks.retVal;
    return frcmcheckboxdataFB;
  }

  FRCMCheckBoxDataFilterBuilder inValues(dynamic pValue) {
    frcmcheckboxdataFB._addedBlocks = setCriteria(
        pValue,
        frcmcheckboxdataFB.parameters,
        param,
        SqlSyntax.IN.replaceAll(SqlSyntax.notKeyword, _waitingNot),
        frcmcheckboxdataFB._addedBlocks);
    _waitingNot = '';
    frcmcheckboxdataFB
            ._addedBlocks.needEndBlock[frcmcheckboxdataFB._blockIndex] =
        frcmcheckboxdataFB._addedBlocks.retVal;
    return frcmcheckboxdataFB;
  }
}
// endregion FRCMCheckBoxDataField

// region FRCMCheckBoxDataFilterBuilder
class FRCMCheckBoxDataFilterBuilder extends SearchCriteria {
  FRCMCheckBoxDataFilterBuilder(FRCMCheckBoxData obj) {
    whereString = '';
    qparams = QueryParams();
    parameters = <DbParameter>[];
    orderByList = <String>[];
    groupByList = <String>[];
    _addedBlocks = AddedBlocks(<bool>[], <bool>[]);
    _addedBlocks.needEndBlock.add(false);
    _addedBlocks.waitingStartBlock.add(false);
    _pagesize = 0;
    _page = 0;
    _obj = obj;
  }
  AddedBlocks _addedBlocks;
  int _blockIndex = 0;
  List<DbParameter> parameters;
  List<String> orderByList;
  FRCMCheckBoxData _obj;
  QueryParams qparams;
  int _pagesize;
  int _page;

  /// put the sql keyword 'AND'
  FRCMCheckBoxDataFilterBuilder get and {
    if (parameters.isNotEmpty) {
      parameters[parameters.length - 1].wOperator = ' AND ';
    }
    return this;
  }

  /// put the sql keyword 'OR'
  FRCMCheckBoxDataFilterBuilder get or {
    if (parameters.isNotEmpty) {
      parameters[parameters.length - 1].wOperator = ' OR ';
    }
    return this;
  }

  /// open parentheses
  FRCMCheckBoxDataFilterBuilder get startBlock {
    _addedBlocks.waitingStartBlock.add(true);
    _addedBlocks.needEndBlock.add(false);
    _blockIndex++;
    if (_blockIndex > 1) {
      _addedBlocks.needEndBlock[_blockIndex - 1] = true;
    }
    return this;
  }

  /// String whereCriteria, write raw query without 'where' keyword. Like this: 'field1 like 'test%' and field2 = 3'
  FRCMCheckBoxDataFilterBuilder where(String whereCriteria,
      {dynamic parameterValue}) {
    if (whereCriteria != null && whereCriteria != '') {
      final DbParameter param = DbParameter(
          columnName: parameterValue == null ? null : '',
          hasParameter: parameterValue != null);
      _addedBlocks = setCriteria(parameterValue ?? 0, parameters, param,
          '($whereCriteria)', _addedBlocks);
      _addedBlocks.needEndBlock[_blockIndex] = _addedBlocks.retVal;
    }
    return this;
  }

  /// page = page number,
  ///
  /// pagesize = row(s) per page
  FRCMCheckBoxDataFilterBuilder page(int page, int pagesize) {
    if (page > 0) {
      _page = page;
    }
    if (pagesize > 0) {
      _pagesize = pagesize;
    }
    return this;
  }

  /// int count = LIMIT
  FRCMCheckBoxDataFilterBuilder top(int count) {
    if (count > 0) {
      _pagesize = count;
    }
    return this;
  }

  /// close parentheses
  FRCMCheckBoxDataFilterBuilder get endBlock {
    if (_addedBlocks.needEndBlock[_blockIndex]) {
      parameters[parameters.length - 1].whereString += ' ) ';
    }
    _addedBlocks.needEndBlock.removeAt(_blockIndex);
    _addedBlocks.waitingStartBlock.removeAt(_blockIndex);
    _blockIndex--;
    return this;
  }

  /// argFields might be String or List<String>.
  ///
  /// Example 1: argFields='name, date'
  ///
  /// Example 2: argFields = ['name', 'date']
  FRCMCheckBoxDataFilterBuilder orderBy(dynamic argFields) {
    if (argFields != null) {
      if (argFields is String) {
        orderByList.add(argFields);
      } else {
        for (String s in argFields as List<String>) {
          if (s != null && s.isNotEmpty) {
            orderByList.add(' $s ');
          }
        }
      }
    }
    return this;
  }

  /// argFields might be String or List<String>.
  ///
  /// Example 1: argFields='field1, field2'
  ///
  /// Example 2: argFields = ['field1', 'field2']
  FRCMCheckBoxDataFilterBuilder orderByDesc(dynamic argFields) {
    if (argFields != null) {
      if (argFields is String) {
        orderByList.add('$argFields desc ');
      } else {
        for (String s in argFields as List<String>) {
          if (s != null && s.isNotEmpty) {
            orderByList.add(' $s desc ');
          }
        }
      }
    }
    return this;
  }

  /// argFields might be String or List<String>.
  ///
  /// Example 1: argFields='field1, field2'
  ///
  /// Example 2: argFields = ['field1', 'field2']
  FRCMCheckBoxDataFilterBuilder groupBy(dynamic argFields) {
    if (argFields != null) {
      if (argFields is String) {
        groupByList.add(' $argFields ');
      } else {
        for (String s in argFields as List<String>) {
          if (s != null && s.isNotEmpty) {
            groupByList.add(' $s ');
          }
        }
      }
    }
    return this;
  }

  /// argFields might be String or List<String>.
  ///
  /// Example 1: argFields='name, date'
  ///
  /// Example 2: argFields = ['name', 'date']
  FRCMCheckBoxDataFilterBuilder having(dynamic argFields) {
    if (argFields != null) {
      if (argFields is String) {
        havingList.add(argFields);
      } else {
        for (String s in argFields as List<String>) {
          if (s != null && s.isNotEmpty) {
            havingList.add(' $s ');
          }
        }
      }
    }
    return this;
  }

  FRCMCheckBoxDataField setField(
      FRCMCheckBoxDataField field, String colName, DbType dbtype) {
    return FRCMCheckBoxDataField(this)
      ..param = DbParameter(
          dbType: dbtype,
          columnName: colName,
          wStartBlock: _addedBlocks.waitingStartBlock[_blockIndex]);
  }

  FRCMCheckBoxDataField _id;
  FRCMCheckBoxDataField get id {
    return _id = setField(_id, 'id', DbType.integer);
  }

  FRCMCheckBoxDataField _userName;
  FRCMCheckBoxDataField get userName {
    return _userName = setField(_userName, 'userName', DbType.text);
  }

  FRCMCheckBoxDataField _userPassword;
  FRCMCheckBoxDataField get userPassword {
    return _userPassword = setField(_userPassword, 'userPassword', DbType.text);
  }

  FRCMCheckBoxDataField _selectedProject;
  FRCMCheckBoxDataField get selectedProject {
    return _selectedProject =
        setField(_selectedProject, 'selectedProject', DbType.text);
  }

  FRCMCheckBoxDataField _selectedPhase;
  FRCMCheckBoxDataField get selectedPhase {
    return _selectedPhase =
        setField(_selectedPhase, 'selectedPhase', DbType.text);
  }

  FRCMCheckBoxDataField _selectedSubPhase;
  FRCMCheckBoxDataField get selectedSubPhase {
    return _selectedSubPhase =
        setField(_selectedSubPhase, 'selectedSubPhase', DbType.text);
  }

  FRCMCheckBoxDataField _selectedCheckBoxTitle;
  FRCMCheckBoxDataField get selectedCheckBoxTitle {
    return _selectedCheckBoxTitle =
        setField(_selectedCheckBoxTitle, 'selectedCheckBoxTitle', DbType.text);
  }

  FRCMCheckBoxDataField _selectedCheckBoxStatus;
  FRCMCheckBoxDataField get selectedCheckBoxStatus {
    return _selectedCheckBoxStatus = setField(
        _selectedCheckBoxStatus, 'selectedCheckBoxStatus', DbType.text);
  }

  FRCMCheckBoxDataField _selectedCheckBoxComments;
  FRCMCheckBoxDataField get selectedCheckBoxComments {
    return _selectedCheckBoxComments = setField(
        _selectedCheckBoxComments, 'selectedCheckBoxComments', DbType.text);
  }

  FRCMCheckBoxDataField _isDeleted;
  FRCMCheckBoxDataField get isDeleted {
    return _isDeleted = setField(_isDeleted, 'isDeleted', DbType.bool);
  }

  bool _getIsDeleted;

  void _buildParameters() {
    if (_page > 0 && _pagesize > 0) {
      qparams
        ..limit = _pagesize
        ..offset = (_page - 1) * _pagesize;
    } else {
      qparams
        ..limit = _pagesize
        ..offset = _page;
    }
    for (DbParameter param in parameters) {
      if (param.columnName != null) {
        if (param.value is List && !param.hasParameter) {
          param.value = param.dbType == DbType.text
              ? '\'${param.value.join('\',\'')}\''
              : param.value.join(',');
          whereString += param.whereString
              .replaceAll('{field}', param.columnName)
              .replaceAll('?', param.value.toString());
          param.value = null;
        } else {
          if (param.value is Map<String, dynamic> &&
              param.value['sql'] != null) {
            param
              ..whereString = param.whereString
                  .replaceAll('?', param.value['sql'].toString())
              ..dbType = DbType.integer
              ..value = param.value['args'];
          }
          whereString +=
              param.whereString.replaceAll('{field}', param.columnName);
        }
        if (!param.whereString.contains('?')) {
        } else {
          switch (param.dbType) {
            case DbType.bool:
              param.value =
                  param.value == null ? null : param.value == true ? 1 : 0;
              param.value2 =
                  param.value2 == null ? null : param.value2 == true ? 1 : 0;
              break;
            case DbType.date:
            case DbType.datetime:
            case DbType.datetimeUtc:
              param.value = param.value == null
                  ? null
                  : (param.value as DateTime).millisecondsSinceEpoch;
              param.value2 = param.value2 == null
                  ? null
                  : (param.value2 as DateTime).millisecondsSinceEpoch;
              break;
            default:
          }
          if (param.value != null) {
            if (param.value is List) {
              for (var p in param.value) {
                whereArguments.add(p);
              }
            } else {
              whereArguments.add(param.value);
            }
          }
          if (param.value2 != null) {
            whereArguments.add(param.value2);
          }
        }
      } else {
        whereString += param.whereString;
      }
    }
    if (FRCMCheckBoxData._softDeleteActivated) {
      if (whereString != '') {
        whereString =
            '${!_getIsDeleted ? 'ifnull(isDeleted,0)=0 AND' : ''} ($whereString)';
      } else if (!_getIsDeleted) {
        whereString = 'ifnull(isDeleted,0)=0';
      }
    }

    if (whereString != '') {
      qparams.whereString = whereString;
    }
    qparams
      ..whereArguments = whereArguments
      ..groupBy = groupByList.join(',')
      ..orderBy = orderByList.join(',')
      ..having = havingList.join(',');
  }

  /// Deletes List<FRCMCheckBoxData> bulk by query
  ///
  /// <returns>BoolResult res.success=Deleted, not res.success=Can not deleted
  Future<BoolResult> delete([bool hardDelete = false]) async {
    _buildParameters();
    var r = BoolResult();

    if (FRCMCheckBoxData._softDeleteActivated && !hardDelete) {
      r = await _obj._mnFRCMCheckBoxData.updateBatch(qparams, {'isDeleted': 1});
    } else {
      r = await _obj._mnFRCMCheckBoxData.delete(qparams);
    }
    return r;
  }

  /// Recover List<FRCMCheckBoxData> bulk by query
  Future<BoolResult> recover() async {
    _getIsDeleted = true;
    _buildParameters();
    print('SQFENTITIY: recover FRCMCheckBoxData bulk invoked');
    return _obj._mnFRCMCheckBoxData.updateBatch(qparams, {'isDeleted': 0});
  }

  /// using:
  ///
  /// update({'fieldName': Value})
  ///
  /// fieldName must be String. Value is dynamic, it can be any of the (int, bool, String.. )
  Future<BoolResult> update(Map<String, dynamic> values) {
    _buildParameters();
    if (qparams.limit > 0 || qparams.offset > 0) {
      qparams.whereString =
          'id IN (SELECT id from FRCMCheckBoxData ${qparams.whereString.isNotEmpty ? 'WHERE ${qparams.whereString}' : ''}${qparams.limit > 0 ? ' LIMIT ${qparams.limit}' : ''}${qparams.offset > 0 ? ' OFFSET ${qparams.offset}' : ''})';
    }
    return _obj._mnFRCMCheckBoxData.updateBatch(qparams, values);
  }

  /// This method always returns FRCMCheckBoxData Obj if exist, otherwise returns null
  ///
  /// bool preload: if true, loads all related child objects (Set preload to true if you want to load all fields related to child or parent)
  ///
  /// ex: toSingle(preload:true) -> Loads all related objects
  ///
  /// List<String> preloadFields: specify the fields you want to preload (preload parameter's value should also be "true")
  ///
  /// ex: toSingle(preload:true, preloadFields:['plField1','plField2'... etc])  -> Loads only certain fields what you specified
  ///
  /// bool loadParents: if true, loads all parent objects until the object has no parent

  ///
  /// <returns>List<FRCMCheckBoxData>
  Future<FRCMCheckBoxData> toSingle(
      {bool preload = false,
      List<String> preloadFields,
      bool loadParents = false,
      List<String> loadedFields}) async {
    _pagesize = 1;
    _buildParameters();
    final objFuture = _obj._mnFRCMCheckBoxData.toList(qparams);
    final data = await objFuture;
    FRCMCheckBoxData obj;
    if (data.isNotEmpty) {
      obj = FRCMCheckBoxData.fromMap(data[0] as Map<String, dynamic>);
    } else {
      obj = null;
    }
    return obj;
  }

  /// This method returns int. [FRCMCheckBoxData]
  ///
  /// <returns>int
  Future<int> toCount(
      [VoidCallback Function(int c) frcmcheckboxdataCount]) async {
    _buildParameters();
    qparams.selectColumns = ['COUNT(1) AS CNT'];
    final frcmcheckboxdatasFuture =
        await _obj._mnFRCMCheckBoxData.toList(qparams);
    final int count = frcmcheckboxdatasFuture[0]['CNT'] as int;
    if (frcmcheckboxdataCount != null) {
      frcmcheckboxdataCount(count);
    }
    return count;
  }

  /// This method returns List<FRCMCheckBoxData> [FRCMCheckBoxData]
  ///
  /// bool preload: if true, loads all related child objects (Set preload to true if you want to load all fields related to child or parent)
  ///
  /// ex: toList(preload:true) -> Loads all related objects
  ///
  /// List<String> preloadFields: specify the fields you want to preload (preload parameter's value should also be "true")
  ///
  /// ex: toList(preload:true, preloadFields:['plField1','plField2'... etc])  -> Loads only certain fields what you specified
  ///
  /// bool loadParents: if true, loads all parent objects until the object has no parent

  ///
  /// <returns>List<FRCMCheckBoxData>
  Future<List<FRCMCheckBoxData>> toList(
      {bool preload = false,
      List<String> preloadFields,
      bool loadParents = false,
      List<String> loadedFields}) async {
    final data = await toMapList();
    final List<FRCMCheckBoxData> frcmcheckboxdatasData =
        await FRCMCheckBoxData.fromMapList(data,
            preload: preload,
            preloadFields: preloadFields,
            loadParents: loadParents,
            loadedFields: loadedFields,
            setDefaultValues: qparams.selectColumns == null);
    return frcmcheckboxdatasData;
  }

  /// This method returns Json String [FRCMCheckBoxData]
  Future<String> toJson() async {
    final list = <dynamic>[];
    final data = await toList();
    for (var o in data) {
      list.add(o.toMap(forJson: true));
    }
    return json.encode(list);
  }

  /// This method returns Json String. [FRCMCheckBoxData]
  Future<String> toJsonWithChilds() async {
    final list = <dynamic>[];
    final data = await toList();
    for (var o in data) {
      list.add(await o.toMapWithChildren(false, true));
    }
    return json.encode(list);
  }

  /// This method returns List<dynamic>. [FRCMCheckBoxData]
  ///
  /// <returns>List<dynamic>
  Future<List<dynamic>> toMapList() async {
    _buildParameters();
    return await _obj._mnFRCMCheckBoxData.toList(qparams);
  }

  /// Returns List<DropdownMenuItem<FRCMCheckBoxData>>
  Future<List<DropdownMenuItem<FRCMCheckBoxData>>> toDropDownMenu(
      String displayTextColumn,
      [VoidCallback Function(List<DropdownMenuItem<FRCMCheckBoxData>> o)
          dropDownMenu]) async {
    _buildParameters();
    final frcmcheckboxdatasFuture = _obj._mnFRCMCheckBoxData.toList(qparams);

    final data = await frcmcheckboxdatasFuture;
    final int count = data.length;
    final List<DropdownMenuItem<FRCMCheckBoxData>> items = []
      ..add(DropdownMenuItem(
        value: FRCMCheckBoxData(),
        child: Text('Select FRCMCheckBoxData'),
      ));
    for (int i = 0; i < count; i++) {
      items.add(
        DropdownMenuItem(
          value: FRCMCheckBoxData.fromMap(data[i] as Map<String, dynamic>),
          child: Text(data[i][displayTextColumn].toString()),
        ),
      );
    }
    if (dropDownMenu != null) {
      dropDownMenu(items);
    }
    return items;
  }

  /// Returns List<DropdownMenuItem<int>>
  Future<List<DropdownMenuItem<int>>> toDropDownMenuInt(
      String displayTextColumn,
      [VoidCallback Function(List<DropdownMenuItem<int>> o)
          dropDownMenu]) async {
    _buildParameters();
    qparams.selectColumns = ['id', displayTextColumn];
    final frcmcheckboxdatasFuture = _obj._mnFRCMCheckBoxData.toList(qparams);

    final data = await frcmcheckboxdatasFuture;
    final int count = data.length;
    final List<DropdownMenuItem<int>> items = []..add(DropdownMenuItem(
        value: 0,
        child: Text('Select FRCMCheckBoxData'),
      ));
    for (int i = 0; i < count; i++) {
      items.add(
        DropdownMenuItem(
          value: data[i]['id'] as int,
          child: Text(data[i][displayTextColumn].toString()),
        ),
      );
    }
    if (dropDownMenu != null) {
      dropDownMenu(items);
    }
    return items;
  }

  /// This method returns Primary Key List SQL and Parameters retVal = Map<String,dynamic>. [FRCMCheckBoxData]
  ///
  /// retVal['sql'] = SQL statement string, retVal['args'] = whereArguments List<dynamic>;
  ///
  /// <returns>List<String>
  Map<String, dynamic> toListPrimaryKeySQL([bool buildParameters = true]) {
    final Map<String, dynamic> _retVal = <String, dynamic>{};
    if (buildParameters) {
      _buildParameters();
    }
    _retVal['sql'] =
        'SELECT `id` FROM FRCMCheckBoxData WHERE ${qparams.whereString}';
    _retVal['args'] = qparams.whereArguments;
    return _retVal;
  }

  /// This method returns Primary Key List<int>.
  /// <returns>List<int>
  Future<List<int>> toListPrimaryKey([bool buildParameters = true]) async {
    if (buildParameters) {
      _buildParameters();
    }
    final List<int> idData = <int>[];
    qparams.selectColumns = ['id'];
    final idFuture = await _obj._mnFRCMCheckBoxData.toList(qparams);

    final int count = idFuture.length;
    for (int i = 0; i < count; i++) {
      idData.add(idFuture[i]['id'] as int);
    }
    return idData;
  }

  /// Returns List<dynamic> for selected columns. Use this method for 'groupBy' with min,max,avg..  [FRCMCheckBoxData]
  ///
  /// Sample usage: (see EXAMPLE 4.2 at https://github.com/hhtokpinar/sqfEntity#group-by)
  Future<List<dynamic>> toListObject() async {
    _buildParameters();

    final objectFuture = _obj._mnFRCMCheckBoxData.toList(qparams);

    final List<dynamic> objectsData = <dynamic>[];
    final data = await objectFuture;
    final int count = data.length;
    for (int i = 0; i < count; i++) {
      objectsData.add(data[i]);
    }
    return objectsData;
  }

  /// Returns List<String> for selected first column
  ///
  /// Sample usage: await FRCMCheckBoxData.select(columnsToSelect: ['columnName']).toListString()
  Future<List<String>> toListString(
      [VoidCallback Function(List<String> o) listString]) async {
    _buildParameters();

    final objectFuture = _obj._mnFRCMCheckBoxData.toList(qparams);

    final List<String> objectsData = <String>[];
    final data = await objectFuture;
    final int count = data.length;
    for (int i = 0; i < count; i++) {
      objectsData.add(data[i][qparams.selectColumns[0]].toString());
    }
    if (listString != null) {
      listString(objectsData);
    }
    return objectsData;
  }
}
// endregion FRCMCheckBoxDataFilterBuilder

// region FRCMCheckBoxDataFields
class FRCMCheckBoxDataFields {
  static TableField _fId;
  static TableField get id {
    return _fId = _fId ?? SqlSyntax.setField(_fId, 'id', DbType.integer);
  }

  static TableField _fUserName;
  static TableField get userName {
    return _fUserName =
        _fUserName ?? SqlSyntax.setField(_fUserName, 'userName', DbType.text);
  }

  static TableField _fUserPassword;
  static TableField get userPassword {
    return _fUserPassword = _fUserPassword ??
        SqlSyntax.setField(_fUserPassword, 'userPassword', DbType.text);
  }

  static TableField _fSelectedProject;
  static TableField get selectedProject {
    return _fSelectedProject = _fSelectedProject ??
        SqlSyntax.setField(_fSelectedProject, 'selectedProject', DbType.text);
  }

  static TableField _fSelectedPhase;
  static TableField get selectedPhase {
    return _fSelectedPhase = _fSelectedPhase ??
        SqlSyntax.setField(_fSelectedPhase, 'selectedPhase', DbType.text);
  }

  static TableField _fSelectedSubPhase;
  static TableField get selectedSubPhase {
    return _fSelectedSubPhase = _fSelectedSubPhase ??
        SqlSyntax.setField(_fSelectedSubPhase, 'selectedSubPhase', DbType.text);
  }

  static TableField _fSelectedCheckBoxTitle;
  static TableField get selectedCheckBoxTitle {
    return _fSelectedCheckBoxTitle = _fSelectedCheckBoxTitle ??
        SqlSyntax.setField(
            _fSelectedCheckBoxTitle, 'selectedCheckBoxTitle', DbType.text);
  }

  static TableField _fSelectedCheckBoxStatus;
  static TableField get selectedCheckBoxStatus {
    return _fSelectedCheckBoxStatus = _fSelectedCheckBoxStatus ??
        SqlSyntax.setField(
            _fSelectedCheckBoxStatus, 'selectedCheckBoxStatus', DbType.text);
  }

  static TableField _fSelectedCheckBoxComments;
  static TableField get selectedCheckBoxComments {
    return _fSelectedCheckBoxComments = _fSelectedCheckBoxComments ??
        SqlSyntax.setField(_fSelectedCheckBoxComments,
            'selectedCheckBoxComments', DbType.text);
  }

  static TableField _fIsDeleted;
  static TableField get isDeleted {
    return _fIsDeleted = _fIsDeleted ??
        SqlSyntax.setField(_fIsDeleted, 'isDeleted', DbType.integer);
  }
}
// endregion FRCMCheckBoxDataFields

//region FRCMCheckBoxDataManager
class FRCMCheckBoxDataManager extends SqfEntityProvider {
  FRCMCheckBoxDataManager()
      : super(EcpsFrcmMmodel(),
            tableName: _tableName,
            primaryKeyList: _primaryKeyList,
            whereStr: _whereStr);
  static final String _tableName = 'FRCMCheckBoxData';
  static final List<String> _primaryKeyList = ['id'];
  static final String _whereStr = 'id=?';
}

//endregion FRCMCheckBoxDataManager
/// Region SEQUENCE IdentitySequence
class IdentitySequence {
  /// Assigns a new value when it is triggered and returns the new value
  /// returns Future<int>
  Future<int> nextVal([VoidCallback Function(int o) nextval]) async {
    final val = await EcpsFrcmMmodelSequenceManager()
        .sequence(SequenceIdentitySequence.getInstance, true);
    if (nextval != null) {
      nextval(val);
    }
    return val;
  }

  /// Get the current value
  /// returns Future<int>
  Future<int> currentVal([VoidCallback Function(int o) currentval]) async {
    final val = await EcpsFrcmMmodelSequenceManager()
        .sequence(SequenceIdentitySequence.getInstance, false);
    if (currentval != null) {
      currentval(val);
    }
    return val;
  }

  /// Reset sequence to start value
  /// returns start value
  Future<int> reset([VoidCallback Function(int o) currentval]) async {
    final val = await EcpsFrcmMmodelSequenceManager()
        .sequence(SequenceIdentitySequence.getInstance, false, reset: true);
    if (currentval != null) {
      currentval(val);
    }
    return val;
  }
}

/// End Region SEQUENCE IdentitySequence

class EcpsFrcmMmodelSequenceManager extends SqfEntityProvider {
  EcpsFrcmMmodelSequenceManager() : super(EcpsFrcmMmodel());
}
// END OF ENTITIES

// BEGIN CONTROLLERS
// BEGIN CONTROLLER (FRCMCheckBoxData)

class FRCMCheckBoxDataController extends FRCMCheckBoxData {
  String formListTitleField = 'userName';
  String formListSubTitleField = 'userPassword';
  static SQFViewList getController = SQFViewList(
    FRCMCheckBoxDataController(),
    primaryKeyName: 'id',
    useSoftDeleting: true,
  );
  Map<String, String> subMenu() {
    final menu = <String, String>{};

    return menu;
  }

  Future<Widget> gotoEdit(dynamic obj) async {
    return FRCMCheckBoxDataAdd(obj == null
        ? FRCMCheckBoxData()
        : await FRCMCheckBoxData().getById(obj['id'] as int) ??
            FRCMCheckBoxData());
  }
}
// END CONTROLLER (FRCMCheckBoxData)

// END OF CONTROLLERS
